[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[program:node-api]
command=/usr/local/bin/node /app/node-api/dist/index.js
directory=/app/node-api
environment=PORT="10001"
autostart=true
autorestart=true
startsecs=3
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:operations]
command=/usr/bin/dotnet /app/operations/IMSOP.OperationsService.dll
environment=ASPNETCORE_HTTP_PORTS="10002"
autostart=true
autorestart=true
startsecs=3
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:supply-chain]
command=/usr/bin/dotnet /app/supply-chain/IMSOP.SupplyChainService.dll
environment=ASPNETCORE_HTTP_PORTS="10003"
autostart=true
autorestart=true
startsecs=3
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:gateway]
command=/usr/bin/dotnet /app/gateway/IMSOP.Gateway.dll
environment=ASPNETCORE_HTTP_PORTS="%(ENV_PORT)s"
autostart=true
autorestart=true
startsecs=3
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
