CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'user',
  password_reset_version INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shipments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tracking_number VARCHAR(100) NOT NULL UNIQUE,
  origin VARCHAR(255) NOT NULL,
  destination VARCHAR(255) NOT NULL,
  carrier VARCHAR(100),
  transport_mode VARCHAR(20),
  latitude NUMERIC(9, 6),
  longitude NUMERIC(9, 6),
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  estimated_arrival TIMESTAMP,
  actual_arrival TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_shipments_status ON shipments (status);

CREATE TABLE IF NOT EXISTS logistics_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider VARCHAR(100) NOT NULL,
  event_id VARCHAR(100) NOT NULL,
  tracking_number VARCHAR(100) NOT NULL,
  event_type VARCHAR(50) NOT NULL,
  payload TEXT NOT NULL,
  occurred_at TIMESTAMP NOT NULL,
  received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_logistics_provider_event UNIQUE (provider, event_id)
);

CREATE INDEX IF NOT EXISTS idx_logistics_tracking ON logistics_events (tracking_number);
CREATE INDEX IF NOT EXISTS idx_logistics_occurred ON logistics_events (occurred_at);

CREATE TABLE IF NOT EXISTS orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number VARCHAR(100) NOT NULL UNIQUE,
  customer_id INTEGER,
  total_amount NUMERIC(10, 2) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (status);

CREATE TABLE IF NOT EXISTS telemetry (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id VARCHAR(100) NOT NULL,
  metric_name VARCHAR(100) NOT NULL,
  metric_value NUMERIC(10, 2) NOT NULL,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_telemetry_device ON telemetry (device_id);
CREATE INDEX IF NOT EXISTS idx_telemetry_metric ON telemetry (metric_name);
CREATE INDEX IF NOT EXISTS idx_telemetry_timestamp ON telemetry (timestamp);
